apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bot-cotacao.fullname" . }}-secret
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.env.BOT_TOKEN | quote }}
  CHAT_ID: {{ .Values.env.CHAT_ID | quote }}
